package enumeracije;

public enum StrucnaSprema {
	
	I_CETIRI_RAZREDA_OSNOVNE,
	II_OSNOVNA_SKOLA,
	III_SSS_SREDNJA_SKOLA,
	IV_SSS_SREDNJA_SKOLA,
	V_VKV_SSS_SREDNJA_SKOLA,
	VI_VISA_SKOLA,
	VII_1_VISOKA_STRUCNA_SPREMA,
	VI_1_OSNOVNE_TROGODISNJE_AKADEMSKE_STUDIJE,
	VI_1_OSNOVNE_TROGODISNJE_STRUKOVNE_STUDIJE,
	VI_2_SPECIJALISTICKE_STRUKOVNE_STUDIJE,
	VII_1A_OSNOVNE_CETVOROGODIŠNJE_AKADEMSKE_STUDIJE,
	VII_1A_INTEGRISANE_MASTER_STUDIJE,
	VII_1B_MASTER,
	VII_2_MAGISTAR_NAUKA,
	VII_2_SPECIJALIZACIJA_U_MEDICINI,
	VII_2_SPECIJALISTICKE_AKADEMSKE_STUDIJE,
	VIII_DOKTOR_NAUKA

}
